using System;

namespace AwesomeBooks.Domain.Entities
{
    public interface IAggregateRoot : IIdentityEntity
    {
        Guid Uid { get; set; }
    }

    public abstract class AggregateRoot : IdentityEntity
    {
        public AggregateRoot()
        {
            Uid = Guid.NewGuid();
        }

        /// <summary>
        /// Entity Universal Identity
        /// </summary>
        /// <remarks>This universal identity is not supposed to be generated by database.</remarks>
        public Guid Uid { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == null || obj.GetType() != GetType())
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            var other = (AggregateRoot)obj;
            return Uid == other.Uid;
        }
    }
}
